spryker-sdk/upgrader

composer.lock
src/Upgrader/Business/Exception/UpgraderFlowException.php
src/Upgrader/Business/PackageManager/Client/ComposerLockDiff/ComposerLockDiffClient.php
src/Upgrader/Business/PackageManager/Client/ComposerLockDiff/Response/ComposerLockDiffResponse.php
src/Upgrader/Business/PackageManager/Response/PackageManagerResponse.php
src/Upgrader/Business/Upgrader/Request/UpgraderRequest.php
src/Upgrader/Business/Upgrader/Response/UpgraderResponse.php
src/Upgrader/Business/Upgrader/Upgrader.php
src/Upgrader/Business/UpgraderBusinessFactory.php
src/Upgrader/Business/VersionControlSystem/Response/VcsResponse.php

Overview
Ticket: https://spryker.atlassian.net/browse/PPLUS-573

PPLUS-573: Added message when project is up to date

---

src/CodeCompliance/Domain/Checks/NotUnique/Method.php

Overview
Ticket: https://spryker.atlassian.net/browse/PPLUS-1176

PPLUS-1176 Message contains project prefix twice

---

README.md

Ticket: https://spryker.atlassian.net/browse/PPLUS-1221

PPLUS-1221: Technical documentation

---

src/Upgrader/Report/Event/ReportListener.php

Ticket: https://spryker.atlassian.net/browse/PPLUS-1388
- Fixed console command status code.

PPLUS-1388: Evaluate command return zero code when issues are found

---

composer.json
composer.lock
src/Upgrader/Commands/Evaluate/Analyze/AnalyzeCommand.php
src/Upgrader/Commands/Evaluate/Report/ReportCommand.php
src/Upgrader/Commands/Upgrade/UpgradeCommand.php

https://spryker.atlassian.net/browse/SDK-592

SDK-592 updates related to the new dependencies

---

src/CodeCompliance/Domain/Checks/NotUnique/DatabaseColumn.php
src/CodeCompliance/Domain/Checks/NotUnique/TransferProperty.php
tests/CodeComplianceTest/Domain/Checks/NotUnique/DatabaseColumnTest.php
tests/CodeComplianceTest/Domain/Checks/NotUnique/TransferPropertyTest.php

Ticket: https://spryker.atlassian.net/browse/PPLUS-1285
ChangeLog: 
* Fixed return code form Evaluate command
* Allow not prefixed sub-entities if a parent is unique on project level

PPLUS-1285: Change the check for unique names of sub entities

---

composer.json
phpcs.xml
src/Core/Domain/ValueObject/Id.php
src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php
src/Upgrader/Console/EvaluateConsole.php
src/Upgrader/Console/EvaluationReportConsole.php
src/Upgrader/Console/UpgraderConsole.php
tests/Core/App/Kernel/TestKernel.php

Change log:
- Use XML configuration for PHP Code Sniffer

Better PHPCS configuration

---

composer.lock

PPLUS-1714: Update integrator

---

src/Core/Infrastructure/Service/ProcessRunnerService.php

Change log:
- Increase process timeout

SDK-1573: Increase process timeout

---

src/Core/Infrastructure/Service/ProcessRunnerService.php
src/Core/Infrastructure/Service/ProcessRunnerServiceInterface.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php

- Fixed timeout time.
https://spryker.atlassian.net/browse/SDK-1573

SDK-1573: Fixed composer timeout

---

README.md
src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
tests/UpgradeTest/Application/Strategy/Common/Step/ComposerLockComparatorStepTest.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php

https://spryker.atlassian.net/browse/SDK-1701
- Created configurable env setting for composer install.

SDK-1701: Created NO_INSTALL_PACKAGES setting for composer

---

composer.lock

Ticket: https://spryker.atlassian.net/browse/SDK-1689

SDK-1689: Fixed wrapped method integration in the integrator.

---

composer.lock
src/Upgrade/Application/Adapter/IntegratorExecutorInterface.php
src/Upgrade/Application/Dto/IntegratorResponseDto.php
src/Upgrade/Application/Dto/StepsResponseDto.php
src/Upgrade/Application/Strategy/Common/Step/ComposerLockComparatorStep.php
src/Upgrade/Application/Strategy/Common/Step/IntegratorStep.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/AggregateReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/SequentialReleaseGroupProcessor.php
src/Upgrade/Infrastructure/Adapter/IntegratorAdapter.php
src/Upgrade/Infrastructure/Executor/IntegratorExecutor.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/Git/GitTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-1611
Change log: 
* Added information about skipped manifests to an PR description

SDK-1611: Provide information about skipped manifests

---

README.md
src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Application/Strategy/Common/Step/IntegratorStep.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
tests/UpgradeTest/Application/Strategy/Common/Step/IntegratorStepTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-1696

SDK-1696: Added config for enabling integrator (default disabled)

---

config/Upgrade/services.yaml
src/Upgrade/Application/Adapter/PackageManagerAdapterInterface.php
src/Upgrade/Application/Dto/StepsResponseDto.php
src/Upgrade/Application/Strategy/AbstractStrategy.php
src/Upgrade/Application/Strategy/Composer/Fixer/FeaturePackageFixerStep.php
src/Upgrade/Application/Strategy/FixerStepInterface.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorInterface.php
src/Upgrade/Infrastructure/PackageManager/ComposerAdapter.php
tests/UpgradeTest/Application/Strategy/Composer/ComposerStrategyTest.php
tests/UpgradeTest/Application/Strategy/Composer/Fixer/FeaturePackageFixerStepTest.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php

https://spryker.atlassian.net/browse/SDK-1733
* Created fixer plugin stack.
* Implemented fixer to split feature-package to packages

SDK-1430: Created Stack fixers and fixer to resolve feature-package

---

src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php

https://spryker.atlassian.net/browse/SDK-1872

SDK-1872: Fixed date in upgrader PR title

---

src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/SDK-1923
Recap:
- fixed formatting bug in created pr description

SDK-1923 fix pr formatting

---

src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/SDK-1924
What's done:
- removed duplicated messages

SDK-1924: Remove warning duplicates

---

src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php

https://spryker.atlassian.net/browse/SDK-1928

SDK-1928: Updated PR message

---

config/Upgrade/services.yaml
src/Upgrade/Infrastructure/Exception/RemoteServerUnreachableException.php
src/Upgrade/Infrastructure/HttpClient/RepeatableHttpClient.php
src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitHub/GitHubClientFactory.php
src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitHub/GitHubSourceCodeProvider.php
src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitLab/GitLabClientFactory.php
src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitLab/GitLabSourceCodeProvider.php
tests/UpgradeTest/Infrastructure/HttpClient/RepeatableHttpClientTest.php

https://spryker.atlassian.net/browse/SDK-1901
what's done:
- Added repeatable HTTP client that makes several attempts to send request in case of connection failures

SDK-1901: Repeatable HTTP client

---

composer.json
composer.lock

Ticket: https://spryker.atlassian.net/browse/SDK-1989

SDK-1989: Updated integrator version.

---

README.md
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
src/Upgrade/Infrastructure/Report/Builder/ReportDtoBuilder.php
src/Upgrade/Infrastructure/Report/Dto/ReportMetadataDto.php
src/Upgrade/Infrastructure/Report/Serializer/Normalizer/ReportNormalizer.php
src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitLab/GitLabSourceCodeProvider.php
tests/UpgradeTest/Infrastructure/Report/Builder/ReportDtoBuilderTest.php
tests/UpgradeTest/Infrastructure/Report/Serializer/Normalizer/ReportNormalizerTest.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/SourceCodeProvider/GitLab/GitLabSourceCodeProviderTest.php

https://spryker.atlassian.net/browse/SDK-1854

SDK-1854: GitLab client updates

---

src/Upgrade/Application/Strategy/AbstractStrategy.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/AggregateReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/ModulePackageFetcher.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/SequentialReleaseGroupProcessor.php
tests/UpgradeTest/Application/Service/UpgradeServiceTest.php
tests/UpgradeTest/Application/Strategy/Composer/ComposerStrategyTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php

https://spryker.atlassian.net/browse/SDK-1927
what was done:
- improved pipeline output
- refactoring

SDK-1927: Pipeline output verbosity and refactoring

---

composer.json
composer.lock
config/Upgrade/services.yaml
src/Upgrade/Application/Adapter/IntegratorExecutorInterface.php
src/Upgrade/Application/Strategy/Common/Step/IntegratorLockStep.php
src/Upgrade/Infrastructure/Executor/IntegratorExecutor.php
tests/UpgradeTest/Application/Strategy/Common/Step/IntegratorLockStepTest.php

https://spryker.atlassian.net/browse/SDK-1964

SDK-1964: Pre check integration lock step

---

config/Upgrade/services.yaml
src/Upgrade/Application/Strategy/Common/PackagePostUpdateHandler/HandlerInterface.php
src/Upgrade/Application/Strategy/Common/PackagePostUpdateHandler/PropelUpdateHandler.php
src/Upgrade/Application/Strategy/Common/Step/PackagePostUpdateStep.php
tests/UpgradeTest/Application/Strategy/Common/PropelUpdateHandler/PropelUpdateHandlerTest.php
tests/UpgradeTest/Application/Strategy/Common/Step/PackagePostUpdateStepTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-2094

SDK-2094: Regenerate Propel models

---

README.md
src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
src/Upgrade/Infrastructure/Report/Builder/ReportDtoBuilder.php
src/Upgrade/Infrastructure/Report/Dto/ReportMetadataDto.php
src/Upgrade/Infrastructure/Report/Serializer/Normalizer/ReportNormalizer.php
tests/UpgradeTest/Infrastructure/Report/Builder/ReportDtoBuilderTest.php
tests/UpgradeTest/Infrastructure/Report/Serializer/Normalizer/ReportNormalizerTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-2056

SDK-2056: Get rid of optional env variable

---

src/ReleaseApp/Application/Configuration/ReleaseAppConstant.php
tests/ReleaseApp/Infrastructure/Service/ReleaseAppServiceTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-2111

SDK-2111: Changed link on majors RGs in PR

---

src/Upgrade/Application/Dto/StepsResponseDto.php
src/Upgrade/Application/Strategy/AbstractStrategy.php
src/Upgrade/Application/Strategy/Common/Step/ComposerLockComparatorStep.php
tests/UpgradeTest/Application/Strategy/Common/Step/ComposerLockComparatorStepTest.php
tests/UpgradeTest/Application/Strategy/Composer/ComposerStrategyTest.php

https://spryker.atlassian.net/browse/SDK-2329

SDK-2329: Stop propagation feature

---

src/ReleaseApp/Infrastructure/Shared/Dto/Collection/ModuleDtoCollection.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/ReleaseGroup/MajorVersionValidator.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/ReleaseGroupSoftValidator.php

https://spryker.atlassian.net/browse/SDK-2347

SDK-2347: Module versions validation improvements

---

src/Upgrade/Application/Strategy/Composer/Fixer/FeaturePackageFixerStep.php
tests/UpgradeTest/Application/Strategy/Composer/Fixer/FeaturePackageFixerStepTest.php

https://spryker.atlassian.net/browse/SDK-2333

SDK-2333: Fix feature package dependency fixer

---

config/DynamicEvaluator/services.yaml
src/Upgrader/UpgraderExtension.php

https://spryker.atlassian.net/browse/SDK-2756

SDK-2756 fix config path

---

src/DynamicEvaluator/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/ProjectExtendedClassesFetcher.php
src/DynamicEvaluator/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/VendorChangedFilesFetcher.php
src/DynamicEvaluator/Application/PublicApiFilePathsProvider/PublicApiFilePathsProvider.php
src/DynamicEvaluator/Application/PublicApiFilePathsProvider/PublicApiFilePathsProviderInterface.php
tests/DynamicEvaluatorTest/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/ProjectExtendedClassesFetcherTest.php
tests/DynamicEvaluatorTest/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/VendorChangedFilesFetcherTest.php
tests/DynamicEvaluatorTest/Application/PublicApiFilePathsProvider/PublicApiFilePathsProviderTest.php

https://spryker.atlassian.net/browse/SDK-2768

SDK-2768 public api files filter

---

README.md
src/ReleaseApp/Application/Service/ReleaseAppService.php
src/ReleaseApp/Application/Service/ReleaseAppServiceInterface.php
src/ReleaseApp/Domain/Client/ReleaseAppClientInterface.php
src/ReleaseApp/Domain/Client/Request/UpgradeReleaseGroupInstructionsRequest.php
src/ReleaseApp/Infrastructure/Client/HttpReleaseAppClient.php
src/ReleaseApp/Infrastructure/Client/Request/HttpUpgradeReleaseGroupInstructionsRequest.php
src/ReleaseApp/Infrastructure/Service/ReleaseAppService.php
src/ReleaseApp/Infrastructure/Service/ReleaseAppServiceInterface.php
src/ReleaseApp/Infrastructure/Shared/Mapper/ReleaseGroupDtoCollectionMapper.php
src/Upgrade/Application/Adapter/ReleaseAppClientAdapterInterface.php
src/Upgrade/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStep.php
src/Upgrade/Infrastructure/Adapter/ReleaseAppClientAdapter.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php
tests/ReleaseApp/Infrastructure/Service/ReleaseAppServiceTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php
tests/data/ReleaseApp/Api/Response/upgrade-release-group-instructions.json

https://spryker.atlassian.net/browse/SDK-2709

SDK-2709 add specific RG updating

---

.github/workflows/dependency-update-pr.yml
.github/workflows/trigger-remote-pr.yml
infrastructure/dev.Dockerfile

https://spryker.atlassian.net/browse/SDK-1805

SDK-1805 CI automation.

---

src/DynamicEvaluator/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/ProjectExtendedClassesFetcher.php
tests/DynamicEvaluatorTest/Application/Checker/ClassExtendsUpdatedPackageChecker/Fetcher/ProjectExtendedClassesFetcherTest.php

https://spryker.atlassian.net/browse/SDK-2845

SDK-2845: Dynamic evaluator issue fix

---

src/Upgrade/Application/Event/UpgraderEventFactory.php
src/Upgrade/Application/Event/UpgraderFinishedEvent.php
src/Upgrade/Application/Event/UpgraderStartedEvent.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
tests/UpgradeTest/Application/Event/UpgraderEventFactoryTest.php

https://spryker.atlassian.net/browse/SDK-2883

SDK-2883 add additional info to nr events

---

config/Upgrade/services.yaml
src/ReleaseApp/Infrastructure/Shared/Dto/Collection/ModuleDtoCollection.php
src/ReleaseApp/Infrastructure/Shared/Dto/ModuleDto.php
src/Upgrade/Application/Adapter/PackageManagerAdapterInterface.php
src/Upgrade/Application/Strategy/Common/Module/BetaMajorModule/BetaMajorModulesFetcher.php
src/Upgrade/Application/Strategy/Common/Module/BetaMajorModule/BetaMajorModulesFetcherInterface.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/BetaMajorPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/ReleaseGroup/MajorVersionValidator.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/Threshold/MajorThresholdValidator.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/Threshold/MinorThresholdValidator.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/Threshold/PatchThresholdValidator.php
src/Upgrade/Infrastructure/PackageManager/ComposerAdapter.php
tests/UpgradeTest/Application/Strategy/Common/Module/BetaMajorModule/BetaMajorModulesFetcherTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/BetaMajorPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php
tests/UpgradeTest/Infrastructure/PackageManager/ComposerAdapterTest.php

https://spryker.atlassian.net/browse/SDK-2751

SDK-2751 beta major validation logic

---

src/ReleaseApp/Domain/Entities/UpgradeInstructionsReleaseGroup.php
src/ReleaseApp/Infrastructure/Shared/Dto/ReleaseGroupDto.php
src/ReleaseApp/Infrastructure/Shared/Mapper/ReleaseGroupDtoCollectionMapper.php
src/Upgrade/Application/Strategy/ReleaseApp/Validator/ReleaseGroup/MajorVersionValidator.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php

https://spryker.atlassian.net/browse/SDK-2396
https://spryker.atlassian.net/browse/SDK-2779

SDK-2396: SDK-2779: extends rg with addition data

---

config/Upgrade/services.yaml
src/Core/Infrastructure/Service/ProcessRunnerService.php
src/Core/Infrastructure/Service/ProcessRunnerServiceInterface.php
src/Upgrade/Application/Strategy/Common/Step/ComposerJsonConstraintFixStep.php
tests/Core/Infrastructure/Service/ProcessRunnerServiceTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ComposerJsonConstraintFixStepTest.php

https://spryker.atlassian.net/browse/SDK-2848

SDK-2848 composer.json fix step

---

composer.json
composer.lock
src/Codebase/Infrastructure/Service/CodebaseService.php
src/Core/Infrastructure/StringHelper.php
src/Upgrade/Application/Adapter/IntegratorExecutorInterface.php
src/Upgrade/Application/Strategy/Common/Step/IntegratorStep.php
src/Upgrade/Infrastructure/Executor/IntegratorExecutor.php
tests/Core/Infrastructure/StringHelperTest.php
tests/UpgradeTest/Application/Strategy/Common/Step/IntegratorStepTest.php
tests/UpgradeTest/Infrastructure/Executor/IntegratorExecutorTest.php

https://spryker.atlassian.net/browse/SDK-4164

SDK-4164: Specific RG modules flow

---

README.md
config/Upgrade/services.yaml
src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/NewPackageFilterItem.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/NewPackageFilterItemTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-4132

SDK-4132: Added NewPackageFilterItem

---

src/DynamicEvaluator/Presentation/Checker/BrokenPhpFilesChecker/ViolationBodyMessageBuilder.php

Ticket: https://spryker.atlassian.net/browse/SDK-4707

SDK-4707: Fixed wrong table structure in PR

---

src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/SDK-4708

SDK-4708: Fixed styles for block

---

src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/SDK-4706

SDK-4706: Adjusted upgrader installed packages message

---

config/Upgrade/services.yaml
src/Core/Infrastructure/Service/ProcessRunnerService.php
src/Upgrade/Application/Executor/StepExecutor.php
src/Upgrade/Application/Service/UpgradeService.php
src/Upgrade/Application/Strategy/AbstractStrategy.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/AggregateReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/BaseReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/SequentialReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStep.php
tests/Core/Infrastructure/Service/ProcessRunnerServiceTest.php
tests/UpgradeTest/Application/Strategy/Composer/ComposerStrategyTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-4940

SDK-4940: The symfony logger was added

---

src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php

Ticket: https://spryker.atlassian.net/browse/SDK-4940

SDK-4940: Disable git hooks

---

src/Upgrade/Application/Strategy/Common/Step/ComposerJsonConstraintFixStep.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ComposerJsonConstraintFixStepTest.php

https://spryker.atlassian.net/browse/SDK-4941

SDK-4941 fix caret composer version

---

src/Upgrade/Application/Dto/ReleaseGroupFilterResponseDto.php
src/Upgrade/Application/Dto/StepsResponseDto.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/AggregateReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/Processor/SequentialReleaseGroupProcessor.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/AlreadyInstalledPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/BetaMajorPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/DevMasterPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/DummyPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/NewPackageFilterItem.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/ReleaseGroupFilter.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/ReleaseGroupFilterInterface.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/ReleaseGroupFilterItemInterface.php
src/Upgrade/Application/Strategy/ReleaseApp/ReleaseGroupFilter/SecurityMajorFilterItem.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/AlreadyInstalledPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/BetaMajorPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/DevMasterPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/DummyPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/NewPackageFilterItemTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/ReleaseGroupFilterTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/SecurityMajorFilterItemTest.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/Git/GitTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-4698

SDK-4698: Show skipped modules

---

config/DynamicEvaluator/checker_phpstan_include_project.neon
config/DynamicEvaluator/services.yaml
src/DynamicEvaluator/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcher.php
tests/DynamicEvaluatorTest/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcherTest.php

https://spryker.atlassian.net/browse/SDK-4970

SDK-4970: Set unlimit memory for phpstan

---

src/Upgrade/Application/Adapter/PackageManagerAdapterInterface.php
src/Upgrade/Application/Strategy/Common/Step/ComposerJsonConstraintFixStep.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorInterface.php
src/Upgrade/Infrastructure/PackageManager/ComposerAdapter.php
tests/UpgradeTest/Application/Strategy/Common/Step/ComposerLockComparatorStepTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ComposerJsonConstraintFixStepTest.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php
tests/UpgradeTest/Infrastructure/PackageManager/ComposerAdapterTest.php

https://spryker.atlassian.net/browse/SDK-5078

SDK-5078: Add composer.lock hash update

---

README.md
config/Upgrade/services.yaml
src/Upgrade/Application/Strategy/Composer/Fixer/AbstractFeaturePackageFixerStep.php
src/Upgrade/Application/Strategy/Composer/Fixer/FeatureDevMasterPackageFixerStep.php
src/Upgrade/Application/Strategy/Composer/Fixer/FeaturePackageFixerStep.php
src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
tests/UpgradeTest/Application/Strategy/Composer/Fixer/FeatureDevMasterPackageFixerStepTest.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php

https://spryker.atlassian.net/browse/SDK-4196
* Created feature update to dev-master fixer

SDK-4196: switching feature to dev master

---

src/DynamicEvaluator/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcher.php
tests/DynamicEvaluatorTest/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcherTest.php

https://spryker.atlassian.net/browse/SDK-5282

SDK-5282: Fixed phpstan error

---

config/Upgrade/services.yaml
src/Upgrade/Application/Dto/StepsResponseDto.php
src/Upgrade/Application/Strategy/Common/Step/ProjectValidationStep.php
src/Upgrade/Application/Validator/ProjectValidator.php
src/Upgrade/Application/Validator/ProjectValidatorInterface.php
src/Upgrade/Application/Validator/ProjectValidatorRuleInterface.php
src/Upgrade/Application/Validator/Rule/PhpcsInstallationValidatorRule.php
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php
tests/UpgradeTest/Application/Strategy/Common/Step/ProjectValidationStepTest.php
tests/UpgradeTest/Application/Validator/ProjectValidatorTest.php
tests/UpgradeTest/Application/Validator/Rule/PhpcsInstallationValidationRuleTest.php
tests/UpgradeTest/Application/Validator/Rule/PhpcsInstallationValidatorRuleTest.php

https://spryker.atlassian.net/browse/SDK-4641

SDK-4641 phpcs project validator

---

src/DynamicEvaluator/Application/Checker/BrokenPhpFilesChecker/EventSubscriber/BrokenPhpFilesCheckerEventSubscriber.php

https://spryker.atlassian.net/browse/SDK-5303

SDK-5303 deactivate phpstan checker

---

src/Upgrade/Application/Strategy/ReleaseApp/Processor/ReleaseGroupProcessorResolver.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Processor/ReleaseGroupProcessorResolverTest.php

https://spryker.atlassian.net/browse/SDK-5306

SDK-5306: Add message for unavailable processor

---

.github/workflows/trigger-remote-pr.yml

All the changes are already merged un the previous PR.

SDK-5357: Dummy change.

---

.github/workflows/trigger-remote-pr.yml

Ticket: https://spryker.atlassian.net/browse/SDK-5357

SKD-5357 Fixed ci.

---

.github/workflows/ci.yml

Ticket: https://spryker.atlassian.net/browse/SDK-5357

SDK-5357: Introduced automerge logic for composer dependencies.

---

src/Upgrade/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutor.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-5464

SDK-5464: Add composer command flag

---

src/Upgrade/Application/Strategy/ReleaseApp/Processor/SequentialReleaseGroupProcessor.php
src/Upgrade/Infrastructure/VersionControlSystem/Git/Git.php
src/Upgrader/Console/UpgraderConsole.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Step/ReleaseGroupUpdateStepTest.php

https://spryker.atlassian.net/browse/SDK-5471

SDK-5471 fix composer issue behavior

---

src/ReleaseApp/Infrastructure/Configuration/ConfigurationProvider.php

https://spryker.atlassian.net/browse/SDK-5465

SDK-5465: Constant renaming

---

src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/SDK-4666

SDK-4666: Add RG title in PR

---

config/Upgrade/services.yaml

https://spryker.atlassian.net/browse/SDK-5543

SDK-5543 fix service naming collisions

---

src/Upgrade/Infrastructure/VersionControlSystem/SourceCodeProvider/GitHub/GitHubSourceCodeProvider.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/SourceCodeProvider/GitHub/GitHubSourceCodeProviderTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-5579

SDK-5579: Added borders near the pull request link

---

composer.json
composer.lock

https://spryker.atlassian.net/browse/SDK-5711

SDK-5711: Updated composer.json

---

.github/workflows/trigger-remote-pr.yml
src/Upgrade/Infrastructure/VersionControlSystem/Generator/PullRequestDataGenerator.php

https://spryker.atlassian.net/browse/FRW-7458

FRW-7458: Fixed upgrader link

---

src/DynamicEvaluator/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcher.php
tests/DynamicEvaluatorTest/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcherTest.php

Ticket: https://spryker.atlassian.net/browse/SUPESC-849

SUPESC-849 Fixed PHPStan formater issue.

---

infrastructure/Dockerfile
infrastructure/dev.Dockerfile

Ticket: https://spryker.atlassian.net/browse/SUPESC-852

SUPESC-852 Fixed cache corruption.

---

.github/workflows/ci.yml
.github/workflows/trigger-remote-pr.yml
README.md
composer.json
composer.lock
docker-compose.yml
infrastructure/Dockerfile
linux-compose.yml

Ticket: https://spryker.atlassian.net/browse/FRW-8801

FRW-8801 Added PHP 8.3 support.

---

config/Upgrade/services.yaml
src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Application/Strategy/Common/Step/OrmModelsRegenerateStep.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php
tests/UpgradeTest/Application/Strategy/Common/Step/OrmModelsRegenerateStepTest.php

Ticket: https://spryker.atlassian.net/browse/SUPESC-873

SUPESC-873 Fixed missing constant error.

---

.github/workflows/ci.yml
README.md
composer.json
composer.lock
src/Codebase/Infrastructure/Dependency/Parser/CodebaseToParserBridge.php
tests/DynamicEvaluatorTest/Application/Checker/BrokenPhpFilesChecker/FileErrorsFetcher/FileErrorsFetcherTest.php
tests/PackageStorage/Application/Fetcher/ClassMetaDataFromFileFetcherTest.php
tests/PackageStorage/Application/Fetcher/ProjectExtendedClassesFetcherTest.php
tests/PackageStorage/Application/PackagesSynchronizer/PackagesSynchronizerTest.php
tests/PackageStorage/Application/PublicApiFilePathsProvider/PublicApiFilePathsProviderTest.php
tests/UpgradeTest/Application/Dto/ResponseDtoTest.php
tests/UpgradeTest/Application/Strategy/Common/IntegratorExecutionValidatorTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/Processor/ReleaseGroupUpgraderTest.php
tests/UpgradeTest/Application/Strategy/ReleaseApp/ReleaseGroupFilter/DummyPackageFilterItemTest.php
tests/UpgradeTest/Infrastructure/EnvParser/EnvFetcherTest.php
tests/UpgradeTest/Infrastructure/PackageManager/CommandExecutor/ComposerCommandExecutorTest.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/SourceCodeProvider/Azure/AzureSourceCodeProviderTest.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/SourceCodeProvider/GitHub/GitHubSourceCodeProviderTest.php
tests/UpgradeTest/Infrastructure/VersionControlSystem/SourceCodeProvider/GitLab/GitLabSourceCodeProviderTest.php
tests/bootstrap.php

Ticket: https://spryker.atlassian.net/browse/FRW-1540

FRW-8773 Added PHP Unit 11 support. 

---

src/Upgrade/Application/Provider/ConfigurationProviderInterface.php
src/Upgrade/Application/Service/UpgradeService.php
src/Upgrade/Infrastructure/Configuration/ConfigurationProvider.php

Ticket: https://spryker.atlassian.net/browse/FRW-9570

FRW-9570 Added log info for `BUDDY_RUN_BRANCH` var. 
